### ISSUE TITLE
Allow command click to open parameter automation

### ISSUE THREAD

**Issue by JonathanDCohen** [benkuper/BenTo#9]
**Is your feature request related to a problem? Please describe.**
I'm working on a MacBook and can't right click, so I can't bring up parameter automation lanes.

**Describe the solution you'd like**
I would like to be able to command click the light block

**Describe alternatives you've considered**
I considered bringing a mouse with me.

This I imagine would be useful anywhere else where a right-click is required.  I'm still new to BenTo so I don't know what all that is.  I'm glad to write a PR if we can agree on the feature.

**Comment by benkuper** [comment]
isn't there a key on mac to simulate a right click ? how do you work on any software that needs right click ??
